### ISSUE TITLE
v1.29 - Filters deleted / working scanner removed

### ISSUE THREAD

**Issue by torantal** [pompobit/ScanGO#19]
Just updated to v1.29 and my filters, customized to my Pokedex and other criteria have been wiped. I understand that new filter features have been introduced but it would have been nice if the current filters had been imported with the new settings set to default. Also currently opening a Pokemon in the filter the first time will show no selections in alert range and show time left. I think this should be shown as default.

Also I was scanning successfully with v1.28 using Pokestumble, which has now been disabled.

**Comment by pompobit** [comment]
I'm really sorry about filters deletion. I was working on new filter options and the old filter should have been correctly imported but I just noticed a bug that caused the deltion.
I didn't want to release the new filter options because they are not testeted and probably don't work well, but I received a lot of e-mail asking about the issues with ScanGO so I hasten to block everything and show the popup in the new version.

But I'm not sleeping so much these night trying to find a solution, so I didn't noticed that bug, now I changed the apk so the old filters should not be deleted anymore, but what is gone is gone, I'm really sorry :\

I know that pokestumble somewhat worked, but ScanGO was hammering their website, so I preferred to block acces until I don't find a solution to not concentrate all the traffic on a single service

**Comment by torantal** [comment]
Ok, perhaps ths will save some other folks filters at least ... ;)

And understandable about Pokestumble.

Right now my favorite solution would be if ScanGo had an option to use the data I'm scanning with PokeSensor on the same device or a combined app of those two, even though it would break with the premise of a solution that doesn't require logins.

Anyway thanks for all the effort and perhaps FPM will be back and all will be good ... : D
